# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa24cf8ab24d7be3650a28d59c0f8d7e832b1f2f37c8c50b34553ed45f9f7afd16ba3c241e1ce5046fa50e53e96a2176d33311624e5a250dc613ea36df3da41b

test:
  secret_key_base: d238f8b453e2b035ea0ba05b0385cbc7aa3c8ffc39405d34f788c2de8b3394e7c38bc40aaab23ff33399819b220f395dac9fa23a2e1533e6966e19ce8ae1246d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
